version: "2"
services:
  database:
    image: mysql:5.6
    container_name: WebCalcData
    restart: always
    environment:
      - TZ=America/Bahia
      - MYSQL_ROOT_PASSWORD=webcalc
      - MYSQL_DATABASE=webcalc
    volumes:
      - ./MYSQL:/var/lib/mysql
      - ./databases:/databases
    networks:
      vpc:
        ipv4_address: 192.168.11.3

  backend:
    build: backend
    container_name: WebCalcBack
    volumes:
      - ./application:/var/www/application
      - ./logs/httpd:/var/log/httpd
      - ./backend/conf:/etc/httpd/conf
    environment:
      - TZ=America/Bahia
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=webcalc
      - DB_USERNAME=root
      - DB_PASSWORD=webcalc
      - SAFRA_ENVIRONMENT=homologation
      - SAFRA_HASH=1DFFA600E6489D3700A39CE2E5BEFD01
      - SAFRA_ID=724980
    expose:
      - 80
    depends_on:
      - database
    networks:
      vpc:
        ipv4_address: 192.168.11.2

networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/29
